# setup conda environment with the below command
# conda env create -f requirements.yml

name: cm4708
dependencies:
  - python=3.10
  - requests=2.28.2
  - pandas=1.5.2
  - matplotlib=3.6.3
  - pymongo=4.3.3
  - python-dotenv=0.21.1
  - scikit-learn=1.2.1
  - tensorflow=2.11.0
